# Netlify部署配置 - 使用HTTPS
baseURL = "https://blog.yxipc.com/"
languageCode = "zh-cn" # 设置语言为中文
title = "我的个人博客"
theme = "hugo-blox-builder"

[params]
  # 设置默认主题为自动（跟随系统），可选：light, dark
  defaultTheme = "auto"

# Netlify优化设置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 构建优化
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false