backend:
  name: git-gateway
  branch: main
  # Netlify Identity配置
  identity_url: "https://blog.yxipc.com/.netlify/identity"
  gateway_url: "https://blog.yxipc.com/.netlify/git/github"

# 媒体文件配置
media_folder: "static/images" # 媒体文件存储路径
public_folder: "/images" # 公开访问路径

# 站点URL配置
site_url: "https://blog.yxipc.com"
display_url: "https://blog.yxipc.com"

locale: 'zh_Hans'

collections:
  - name: "posts"
    label: "博客文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "摘要", name: "summary", widget: "text", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "特色图片", name: "image", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "authors"
    label: "作者管理"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "姓名", name: "title", widget: "string"}
      - {label: "角色", name: "role", widget: "string", required: false}
      - {label: "头像", name: "avatar_filename", widget: "image", required: false}
      - {label: "个人简介", name: "bio", widget: "text", required: false}
      - {label: "兴趣爱好", name: "interests", widget: "list", required: false}
      - {label: "邮箱", name: "email", widget: "string", required: false}
      - {label: "超级用户", name: "superuser", widget: "boolean", default: false}
      - label: "社交链接"
        name: "social"
        widget: "list"
        required: false
        fields:
          - {label: "图标", name: "icon", widget: "string"}
          - {label: "图标包", name: "icon_pack", widget: "select", options: ["fas", "fab", "ai"]}
          - {label: "链接", name: "link", widget: "string"}
      - label: "教育背景"
        name: "education"
        widget: "object"
        required: false
        fields:
          - label: "课程"
            name: "courses"
            widget: "list"
            fields:
              - {label: "课程名称", name: "course", widget: "string"}
              - {label: "学校", name: "institution", widget: "string"}
              - {label: "年份", name: "year", widget: "number"}
      - {label: "内容", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "页面管理"
    files:
      - label: "首页"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "日期", name: "date", widget: "datetime"}
          - {label: "类型", name: "type", widget: "hidden", default: "landing"}
          - label: "页面区块"
            name: "sections"
            widget: "list"
            types:
              - label: "Hero区块"
                name: "hero"
                widget: "object"
                fields:
                  - {label: "区块类型", name: "block", widget: "hidden", default: "hero"}
                  - label: "内容"
                    name: "content"
                    widget: "object"
                    fields:
                      - {label: "标题", name: "title", widget: "markdown"}
                      - {label: "文本", name: "text", widget: "markdown"}
                      - label: "图片"
                        name: "image"
                        widget: "object"
                        required: false
                        fields:
                          - {label: "文件名", name: "filename", widget: "string"}
              - label: "关于我区块"
                name: "about"
                widget: "object"
                fields:
                  - {label: "区块类型", name: "block", widget: "hidden", default: "about.biography"}
                  - {label: "ID", name: "id", widget: "string", default: "about"}
                  - label: "内容"
                    name: "content"
                    widget: "object"
                    fields:
                      - {label: "标题", name: "title", widget: "string"}
                      - {label: "用户名", name: "username", widget: "string", default: "admin"}
              - label: "文章列表区块"
                name: "collection"
                widget: "object"
                fields:
                  - {label: "区块类型", name: "block", widget: "hidden", default: "collection"}
                  - {label: "ID", name: "id", widget: "string", default: "posts"}
                  - label: "内容"
                    name: "content"
                    widget: "object"
                    fields:
                      - {label: "标题", name: "title", widget: "string"}
                      - {label: "副标题", name: "subtitle", widget: "string", required: false}
                      - {label: "数量", name: "count", widget: "number", default: 5}
                      - label: "过滤器"
                        name: "filters"
                        widget: "object"
                        fields:
                          - {label: "文件夹", name: "folders", widget: "list", default: ["posts"]}
                      - {label: "排序", name: "order", widget: "select", options: ["desc", "asc"], default: "desc"}